annotations:
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 10.0.0.0/30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -188.0
    y1: -43.5
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 10.0.0.4/30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 101.0
    y1: -43.5
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 1.1.1.1/32
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -408.0
    y1: -70.5
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 3.3.3.3/32
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 326.0
    y1: -69.5
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: Tunnel 172.16.0.0/30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -80.0
    y1: -137.5
    z_index: 2
  - border_color: '#808080FF'
    border_radius: 0
    border_style: ''
    color: '#D1ECF8'
    rotation: 0
    thickness: 1
    type: rectangle
    x1: -277.40441148009916
    y1: -142.7681399260834
    x2: 576.0000000000002
    y2: 25.0
    z_index: 0
smart_annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 3588 bytes
          !
          ! Last configuration change at 00:55:18 UTC Wed Jan 7 2026
          !
          version 15.9
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          !
          hostname R3
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          !
          no aaa new-model
          !
          !
          !
          mmi polling-interval 60
          no mmi auto-configure
          no mmi pvc
          mmi snmp-timeout 180
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip cef
          no ipv6 cef
          !
          multilink bundle-name authenticated
          !
          !
          !
          !
          !
          redundancy
          !
          !
          !
          !
          !
          !
          !
          crypto isakmp policy 10
           encr aes
           authentication pre-share
           group 14
          crypto isakmp key SECRETKEY address 10.0.0.2
          !
          !
          crypto ipsec transform-set VTISET ah-sha-hmac esp-aes
           mode tunnel
          !
          crypto ipsec profile VTIPROFILE
           set transform-set VTISET
          !
          !
          !
          !
          !
          !
          !
          interface Loopback0
           ip address 3.3.3.3 255.255.255.255
           ip ospf 1 area 0
          !
          interface Tunnel10
           ip address 172.16.0.2 255.255.255.252
           ip ospf 1 area 0
           tunnel source 10.0.0.6
           tunnel mode ipsec ipv4
           tunnel destination 10.0.0.2
           tunnel protection ipsec profile VTIPROFILE
          !
          interface GigabitEthernet0/0
           ip address 10.0.0.6 255.255.255.252
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/1
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/2
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/3
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          router ospf 1
          !
          ip forward-protocol nd
          !
          !
          no ip http server
          no ip http secure-server
          ip route 10.0.0.0 255.255.255.252 GigabitEthernet0/0
          !
          ipv6 ioam timestamp
          !
          !
          !
          control-plane
          !
          banner exec ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner incoming ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner login ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login
           transport input none
          !
          no scheduler allocate
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: R3
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: 292
    y: -63
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        type: physical
        slot: 0
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        type: physical
        slot: 1
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        type: physical
        slot: 2
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        type: physical
        slot: 3
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 3588 bytes
          !
          ! Last configuration change at 00:55:19 UTC Wed Jan 7 2026
          !
          version 15.9
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          !
          hostname R1
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          !
          no aaa new-model
          !
          !
          !
          mmi polling-interval 60
          no mmi auto-configure
          no mmi pvc
          mmi snmp-timeout 180
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip cef
          no ipv6 cef
          !
          multilink bundle-name authenticated
          !
          !
          !
          !
          !
          redundancy
          !
          !
          !
          !
          !
          !
          !
          crypto isakmp policy 10
           encr aes
           authentication pre-share
           group 14
          crypto isakmp key SECRETKEY address 10.0.0.6
          !
          !
          crypto ipsec transform-set VTISET ah-sha-hmac esp-aes
           mode tunnel
          !
          crypto ipsec profile VTIPROFILE
           set transform-set VTISET
          !
          !
          !
          !
          !
          !
          !
          interface Loopback0
           ip address 1.1.1.1 255.255.255.255
           ip ospf 1 area 0
          !
          interface Tunnel10
           ip address 172.16.0.1 255.255.255.252
           ip ospf 1 area 0
           tunnel source 10.0.0.2
           tunnel mode ipsec ipv4
           tunnel destination 10.0.0.6
           tunnel protection ipsec profile VTIPROFILE
          !
          interface GigabitEthernet0/0
           ip address 10.0.0.2 255.255.255.252
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/1
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/2
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/3
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          router ospf 1
          !
          ip forward-protocol nd
          !
          !
          no ip http server
          no ip http secure-server
          ip route 10.0.0.4 255.255.255.252 GigabitEthernet0/0
          !
          ipv6 ioam timestamp
          !
          !
          !
          control-plane
          !
          banner exec ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner incoming ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner login ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login
           transport input none
          !
          no scheduler allocate
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: R1
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: -275
    y: -67
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        type: physical
        slot: 0
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        type: physical
        slot: 1
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        type: physical
        slot: 2
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        type: physical
        slot: 3
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 3003 bytes
          !
          ! Last configuration change at 00:55:20 UTC Wed Jan 7 2026
          !
          version 15.9
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          !
          hostname R2
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          !
          no aaa new-model
          !
          !
          !
          mmi polling-interval 60
          no mmi auto-configure
          no mmi pvc
          mmi snmp-timeout 180
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip cef
          no ipv6 cef
          !
          multilink bundle-name authenticated
          !
          !
          !
          !
          !
          redundancy
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface GigabitEthernet0/0
           ip address 10.0.0.1 255.255.255.252
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/1
           ip address 10.0.0.5 255.255.255.252
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/2
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/3
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          ip forward-protocol nd
          !
          !
          no ip http server
          no ip http secure-server
          !
          ipv6 ioam timestamp
          !
          !
          !
          control-plane
          !
          banner exec ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner incoming ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner login ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login
           transport input none
          !
          no scheduler allocate
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: R2
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: 15
    y: -65
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        type: physical
        slot: 0
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        type: physical
        slot: 1
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        type: physical
        slot: 2
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        type: physical
        slot: 3
links:
  - id: l0
    n1: n1
    n2: n2
    i1: i1
    i2: i1
    conditioning: {}
    label: ios-0-GigabitEthernet0/0<->ios-1-GigabitEthernet0/0
  - id: l1
    n1: n2
    n2: n0
    i1: i2
    i2: i1
    conditioning: {}
    label: ios-1-GigabitEthernet0/1<->ios-2-GigabitEthernet0/0
lab:
  description: ''
  notes: ''
  title: GRE Tunnel
  version: 0.3.0
